### ISSUE TITLE
Endfix replacing lists with vectors on some inner lists.

### ISSUE THREAD

**Issue by sstanfield** [sstanfield/slsh#47]
Can recreate with:
(defn defn-test (x y) (set 'x (* x 2))(+ x y))

Note with endfix on the output will be:
(fn (x y)
    (block defn-test
        #(set (quote x) #(* x 2))
        #(+ x y)))

The two vectors should be lists.

**Comment by gpwclark** [comment]
fix in fb3ac3bf7afbbfb51bf882a6202990e46a83703b
